"""
diagnostics/Registry.py
=======================
全域 IO 登錄表。

使用方式：
    @register(
        module="Data",
        inputs={"ticker": "str", "days": "int"},
        outputs={"return": "pd.DataFrame"},
        notes="含 24h 快取"
    )
    def fetch(ticker: str, days: int) -> pd.DataFrame:
        ...

    export_md()        # 自動生成 io_map.md
    show_registry()    # terminal 預覽
"""

from __future__ import annotations

import functools
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, Optional


# ── 資料結構 ────────────────────────────────────────────────────────────────

@dataclass
class IOSignature:
    module:      str
    name:        str
    inputs:      dict[str, str]
    outputs:     dict[str, str]
    notes:       str = ""
    call_count:  int = 0
    last_called: Optional[float] = None


# ── 全域登錄表 ───────────────────────────────────────────────────────────────

_REGISTRY: dict[str, IOSignature] = {}


# ── 裝飾器 ──────────────────────────────────────────────────────────────────

def register(
    module:  str,
    inputs:  dict[str, str],
    outputs: dict[str, str],
    notes:   str = "",
) -> Callable:
    """
    登錄函數的 IO 簽名，並自動追蹤 call_count / last_called。

    Args:
        module:  模組分類名稱，例如 "Data"、"Proc"、"Env"、"Agent"
        inputs:  輸入參數型別描述，格式 {"param_name": "type_str"}
        outputs: 輸出型別描述，格式 {"return": "type_str"}
        notes:   備註說明

    Returns:
        裝飾器函數
    """
    def decorator(fn: Callable) -> Callable:
        key = f"{module}.{fn.__qualname__}"
        sig = IOSignature(
            module=module,
            name=fn.__qualname__,
            inputs=inputs,
            outputs=outputs,
            notes=notes,
        )
        # 同一函數重複登錄時，覆蓋舊記錄
        _REGISTRY[key] = sig

        @functools.wraps(fn)
        def wrapper(*args, **kwargs):
            sig.call_count += 1
            sig.last_called = time.time()
            return fn(*args, **kwargs)

        return wrapper
    return decorator


# ── 查詢 API ─────────────────────────────────────────────────────────────────

def show_registry(module: Optional[str] = None) -> None:
    """
    印出登錄表，可按模組篩選。

    Args:
        module: 若指定，只顯示該模組的記錄；None 則顯示全部
    """
    rows = list(_REGISTRY.values())
    if module:
        rows = [r for r in rows if r.module == module]

    if not rows:
        print("（登錄表為空）")
        return

    print(f"\n{'─' * 72}")
    print(f"  {'MODULE':<10} {'FUNCTION':<30} {'CALLS':>6}  NOTES")
    print(f"{'─' * 72}")
    for r in rows:
        print(f"  {r.module:<10} {r.name:<30} {r.call_count:>6}  {r.notes}")
        inp = ", ".join(f"{k}: {v}" for k, v in r.inputs.items())
        out = ", ".join(f"{v}" for v in r.outputs.values())
        print(f"  {'':10} IN : {inp}")
        print(f"  {'':10} OUT: {out}")
    print(f"{'─' * 72}\n")


# ── 文件生成 ─────────────────────────────────────────────────────────────────

def export_md(path: str = "diagnostics/io_map.md") -> None:
    """
    自動生成 io_map.md，不需手動維護。

    Args:
        path: 輸出路徑，預設為 diagnostics/io_map.md
    """
    output_path = Path(path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# IO Map",
        "",
        "_Auto-generated by `diagnostics/Registry.py`. Do not edit manually._",
        "",
        f"_Last updated: {time.strftime('%Y-%m-%d %H:%M:%S')}_",
        "",
        "| Module | Function | Input | Output | Notes | Calls |",
        "|--------|----------|-------|--------|-------|------:|",
    ]

    for r in _REGISTRY.values():
        inp = ", ".join(f"`{k}: {v}`" for k, v in r.inputs.items())
        out = ", ".join(f"`{v}`" for v in r.outputs.values())
        lines.append(
            f"| {r.module} | `{r.name}` | {inp} | {out} | {r.notes} | {r.call_count} |"
        )

    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"✅ IO Map exported → {output_path.resolve()}")